import { useEffect, useMemo, useRef, useState, type ChangeEvent, type FormEvent, type ReactNode } from "react";
import { invoke } from "@tauri-apps/api/core";
import { open } from "@tauri-apps/plugin-dialog";

type Dashboard = { receivedToday:number; tailoredToday:number; readyToDeliver:number };
type WorkBoardItem = { orderId:number; invoiceNumber:string; customerName:string; customerCode:string; quantity:number; status:string };
type CurrentSession = { startedAt:string };
type SessionEntry = { startedAt:string; endedAt:string };
type DisplaySession = { start:Date; end:Date; active:boolean; key:string };
type Customer = { id:number; code:string; name:string; phone:string };
type CustomerSearchItem = Customer & { invoiceCount:number; lastInvoiceAt:string };
type DesignOption = { id:number; category:string; name:string; imageData:string };
type InvoiceRecord = { id:number; invoiceNumber:string; createdAt:string };
type SavedInvoice = {
  id:number;invoiceNumber:string;customerId:number;createdAt:string;weight:string;deliveryDate:string;
  dayCount:number;totalThobes:number;totalPrice:string;paidAmount:string;paymentMethod:string;discount:string;
  notes:string;measurementsJson:string;fabricJson:string;designsJson:string;detailsJson:string
};
type StorageInfo = { folder:string; databasePath:string; isCustom:boolean };
type SleeveMode = "سادة"|"كبك";
type CollarMode = "قلاب"|"سادة";
type NeckButtonType = "طقطق"|"بلاستيك";
type ThobeDraft = {measurements:Record<string,string>;fabric:Record<string,string>;designs:Record<string,DesignOption|undefined>;thobeType:string;sleeveMode:SleeveMode;collarMode:CollarMode;neckButtonCount:"1"|"2";neckButtonType:NeckButtonType;notes:string};
type PrintTarget = "measurements"|"receipt"|"laundry";
type View = "dashboard"|"add-customer"|"customers"|"order"|"settings";

const dateFormat = new Intl.DateTimeFormat("ar-SA-u-ca-gregory-nu-latn",{weekday:"long",day:"2-digit",month:"long",year:"numeric"});
const shortDateFormat = new Intl.DateTimeFormat("ar-SA-u-ca-gregory-nu-latn",{day:"2-digit",month:"2-digit",year:"numeric"});
const hijriDateFormat = new Intl.DateTimeFormat("ar-SA-u-ca-islamic-umalqura-nu-latn",{weekday:"long",day:"2-digit",month:"long",year:"numeric"});
const timeFormat = new Intl.DateTimeFormat("ar-SA-u-nu-latn",{hour:"2-digit",minute:"2-digit",hour12:false});
const numberFormat = new Intl.NumberFormat("en-US",{useGrouping:false,maximumFractionDigits:2});

const bodyLengthFields = ["طول أمام","طول خلف"] as const;
const bodyFields = ["طول أمام","طول خلف","الكتف","مقاس الصدر","مقاس العرض","مقاس عند الجيوب","مقاس الخطوة تحت","الخانة تحت"] as const;
const bodySingleFields = bodyFields.filter(field=>!(bodyLengthFields as readonly string[]).includes(field));
const sleeveBaseFields = ["طول اليد","سعة اليد من فوق","سعة اليد من الوسط","سعة اليد من تحت"] as const;
const sleevePlainFields = ["الخبنة"] as const;
const sleeveCuffFields = ["طول الكبك","عرض الكبك"] as const;
const collarFields = ["محيط الرقبة","مقاس القلاب الأول","مقاس القلاب الثاني","مقاس الرقبة السادة"] as const;
const measurementFields = [...bodyFields,...sleeveBaseFields,...sleevePlainFields,...sleeveCuffFields,...collarFields] as const;
const fabricFields = ["ID القماش","اسم القماش","طول الجنزور"] as const;
const thobeTypes = ["سعودي","قطري","إماراتي","كويتي"] as const;
const defaultCategories = ["نوع الثوب","اليد السادة","الكبك","القلاب","الرقبة السادة","الجيب","السحب","الجنب وأسفل الثوب","التطريز","الأزرار","الجنزور والتخليص"];

function blankFields(fields:readonly string[]){return Object.fromEntries(fields.map(field=>[field,""])) as Record<string,string>}
function blankThobe():ThobeDraft{return {measurements:blankFields(measurementFields),fabric:blankFields(fabricFields),designs:{},thobeType:"سعودي",sleeveMode:"سادة",collarMode:"قلاب",neckButtonCount:"1",neckButtonType:"طقطق",notes:""}}
function cloneThobe(thobe:ThobeDraft):ThobeDraft{return {...thobe,measurements:{...thobe.measurements},fabric:{...thobe.fabric},designs:{...thobe.designs}}}
function databaseDate(value:string){return new Date(value.replace(" ","T"));}
function dayKey(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}
function dateInputValue(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}
function deliveryAfter(days:number){const date=new Date();date.setHours(0,0,0,0);date.setDate(date.getDate()+days);return dateInputValue(date)}
function sequenceNumber(value:string){const digits=String(value??"").replace(/\D/g,"");return digits?digits.replace(/^0+(?=\d)/,""):value}
function normalizedArabic(value:string){return value.trim().toLocaleLowerCase("ar").replace(/[أإآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/\s+/g," ")}
function comparableThobe(thobe:ThobeDraft){const designs=Object.fromEntries(Object.entries(thobe.designs).filter((entry):entry is [string,DesignOption]=>Boolean(entry[1])).sort(([a],[b])=>a.localeCompare(b)).map(([category,option])=>[category,option.id]));return JSON.stringify({measurements:thobe.measurements,fabric:thobe.fabric,designs,thobeType:thobe.thobeType,sleeveMode:thobe.sleeveMode,collarMode:thobe.collarMode,neckButtonCount:thobe.neckButtonCount,neckButtonType:thobe.neckButtonType,notes:thobe.notes})}
function latinDigits(value:string){return value.replace(/[٠-٩۰-۹]/g,digit=>String("٠١٢٣٤٥٦٧٨٩۰۱۲۳۴۵۶۷۸۹".indexOf(digit)%10));}
function numericValue(value:string){return Number(latinDigits(value).replace(/[^0-9.-]/g,""))||0}
function objectValue(value:unknown):Record<string,unknown>{return value!==null&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}
function parseObject(value:string):Record<string,unknown>{try{return objectValue(JSON.parse(value))}catch{return {}}}
function textRecord(value:unknown):Record<string,string>{return Object.fromEntries(Object.entries(objectValue(value)).map(([key,item])=>[key,item===null||item===undefined?"":String(item)]));}
function durationLabel(milliseconds:number){const totalMinutes=Math.max(0,Math.floor(milliseconds/60000));const hours=Math.floor(totalMinutes/60);const minutes=totalMinutes%60;if(hours===0)return `${numberFormat.format(minutes)} دقيقة`;return `${numberFormat.format(hours)} ساعة${minutes?` و ${numberFormat.format(minutes)} دقيقة`:""}`;}
function imageFromFile(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error("read"));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error("image"));image.onload=()=>{const scale=Math.min(1,1200/Math.max(image.width,image.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext("2d")?.drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.84));};image.src=String(reader.result);};reader.readAsDataURL(file);});}

type IconName = "person"|"search"|"whatsapp"|"finance"|"supplier"|"income"|"delivery"|"notes"|"report"|"access"|"inventory";
const rightMenu:[string,IconName][] = [["إضافة عميل","person"],["بحث عن عميل","search"],["إعلانات واتساب","whatsapp"],["المعاملات المالية","finance"],["الموردون","supplier"]];
const leftMenu:[string,IconName][] = [["دخل إضافي","income"],["توزيع الثياب","delivery"],["ملاحظات جديدة","notes"],["تقرير يومي","report"],["الصلاحيات","access"],["المخزون","inventory"]];
const workStatuses = ["انتظار القص","عند الخياط","في المغسلة","في المحل بانتظار التسليم","تم التسليم"] as const;

function Icon({name}:{name:IconName}){
  const common={fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const};
  const paths:Record<IconName,ReactNode>={person:<><circle cx="10" cy="8" r="3"/><path d="M4 19c.8-3.4 2.8-5 6-5s5.2 1.6 6 5"/><path d="M18 9v6M15 12h6"/></>,search:<><circle cx="10" cy="10" r="5"/><path d="m14 14 5 5"/></>,whatsapp:<><path d="M18.5 10.5a8.5 8.5 0 0 1-10.7 8.2L4 20l1.3-3.6A8.5 8.5 0 1 1 18.5 10.5Z"/><path d="M8 8.3c.5 2.8 2.4 4.6 5.2 5.2l1.3-1.1 1.6.8c-.4 1.6-1.4 2-2.4 1.7-3.9-1.2-6.3-3.6-7.4-7.4-.3-1 .1-2 1.7-2.4l.8 1.6Z"/></>,finance:<><path d="M3.5 7.5h17v11h-17z"/><path d="M3.5 10h17M8 15h3"/></>,supplier:<><path d="M4 9h16v11H4z"/><path d="M7 9V6h10v3M8 14h8"/></>,income:<><path d="M4 16 9 11l3 3 7-8"/><path d="M14 6h5v5"/></>,delivery:<><path d="M3 8h11v9H3zM14 11h3l3 3v3h-6z"/><circle cx="7" cy="18" r="1.5"/><circle cx="17" cy="18" r="1.5"/></>,notes:<><path d="M5 3.5h14v17H5z"/><path d="M8 8h8M8 12h8M8 16h5"/></>,report:<><path d="M4 20V4"/><path d="M7 17v-5M12 17V8M17 17V5"/></>,access:<><path d="M12 3 19 6v5c0 4.2-2.6 7.3-7 10-4.4-2.7-7-5.8-7-10V6z"/><path d="M9.5 12 11 13.5l3.5-4"/></>,inventory:<><path d="m4 8 8-4 8 4-8 4zM4 8v8l8 4 8-4V8M12 12v8"/></>};
  return <svg viewBox="0 0 24 24" aria-hidden="true" {...common}>{paths[name]}</svg>;
}
function MenuCard({label,icon,onSelect}:{label:string;icon:IconName;onSelect?:()=>void}){return <button className={`nav-card ${onSelect?"is-enabled":"is-locked"}`} type="button" onClick={onSelect} aria-disabled={!onSelect} tabIndex={onSelect?0:-1}><span className="nav-icon"><Icon name={icon}/></span><span>{label}</span></button>}

type SheetProps={customer:Customer;invoice:InvoiceRecord|null;weight:string;deliveryDate:string;totalThobes:string;measurements:Record<string,string>;fabric:Record<string,string>;designs:Record<string,DesignOption|undefined>;thobeType:string;sleeveMode:SleeveMode;collarMode:CollarMode;neckButtonCount:"1"|"2";neckButtonType:NeckButtonType;notes:string;sheetLabel?:string};
function MeasurementSheet(props:SheetProps){
  const sleeveCategory=props.sleeveMode==="سادة"?"اليد السادة":"الكبك";
  const collarCategory=props.collarMode==="قلاب"?"القلاب":"الرقبة السادة";
  const paperPhoto=(category:string,fallback:string)=>{const option=props.designs[category];return <figure className="paper-feature-photo">{option?<img src={option.imageData} alt={option.name}/>:<span>بدون صورة</span>}<figcaption>{option?.name||fallback}</figcaption></figure>};
  const paperRows=(fields:readonly string[])=>fields.map(field=><p key={field}><span>{field}</span><b className="numeric">{props.measurements[field]||"—"}</b></p>);
  return <article className="paper measurement-paper" dir="rtl">
    <header><div><b>ورقة مقاسات الخياط</b><small>TAILOR {props.sheetLabel&&`— ${props.sheetLabel}`}</small></div><div><strong>رقم الفاتورة: <span className="numeric">{props.invoice?sequenceNumber(props.invoice.invoiceNumber):"مسودة"}</span></strong><small className="numeric">{shortDateFormat.format(new Date())}</small></div></header>
    <section className="paper-customer"><span>العميل: <b>{props.customer.name}</b></span><span>رقم العميل: <b className="numeric">{sequenceNumber(props.customer.code)}</b></span><span>الجوال: <b className="numeric">{props.customer.phone}</b></span><span>تاريخ التفصيل: <b className="numeric">{props.invoice?shortDateFormat.format(databaseDate(props.invoice.createdAt)):shortDateFormat.format(new Date())}</b></span><span>تاريخ التسليم: <b className="numeric">{props.deliveryDate||"—"}</b></span><span>الوزن: <b className="numeric">{props.weight||"—"}</b></span><span>عدد الثياب: <b className="numeric">{props.totalThobes||"1"}</b></span></section>
    <section className="paper-work-grid">
      <article className="paper-work-card"><h3>الثوب والجسم</h3>{paperPhoto("نوع الثوب",props.thobeType)}<div className="paper-values"><p><span>نوع الثوب</span><b>{props.thobeType}</b></p><p><span>الطول — أمام / خلف</span><b className="numeric">{props.measurements["طول أمام"]||"—"} / {props.measurements["طول خلف"]||"—"}</b></p>{paperRows(bodySingleFields)}</div></article>
      <article className="paper-work-card"><h3>اليد</h3>{paperPhoto(sleeveCategory,props.sleeveMode)}<div className="paper-values"><p><span>نوع اليد</span><b>{props.sleeveMode}</b></p>{paperRows(sleeveBaseFields)}{paperRows(props.sleeveMode==="سادة"?sleevePlainFields:sleeveCuffFields)}</div></article>
      <article className="paper-work-card"><h3>الرقبة</h3>{paperPhoto(collarCategory,props.collarMode)}<div className="paper-values"><p><span>نوع الرقبة</span><b>{props.collarMode}</b></p>{paperRows(["محيط الرقبة"])}{props.collarMode==="قلاب"?<p><span>مقاس القلاب</span><b className="numeric">{props.measurements["مقاس القلاب الأول"]||"—"} — {props.measurements["مقاس القلاب الثاني"]||"—"}</b></p>:paperRows(["مقاس الرقبة السادة"])}<p><span>أزرار الرقبة</span><b><span className="numeric">{props.neckButtonCount}</span> — {props.neckButtonType}</b></p></div></article>
      <article className="paper-work-card paper-detail-card"><h3>الجيب والواجهة</h3><div className="paper-double-photo">{paperPhoto("الجيب","بدون جيب")}{paperPhoto("السحب","بدون سحب")}</div><div className="paper-values">{fabricFields.map(field=><p key={field}><span>{field}</span><b className={field==="اسم القماش"?"":"numeric"}>{props.fabric[field]||"—"}</b></p>)}{props.notes&&<p className="paper-note"><span>ملاحظة</span><b>{props.notes}</b></p>}</div></article>
    </section>
  </article>;
}
function CustomerReceiptSheet({customer,invoice,thobes,total,paid,discount,remaining,paymentMethod,deliveryDate}:{customer:Customer;invoice:InvoiceRecord|null;thobes:ThobeDraft[];total:number;paid:number;discount:number;remaining:number;paymentMethod:string;deliveryDate:string}){return <article className="paper receipt-paper customer-receipt" dir="rtl"><h2>أناقة التميز</h2><p>فاتورة السعر للعميل</p><hr/><div><span>رقم الفاتورة</span><b className="numeric">{invoice?sequenceNumber(invoice.invoiceNumber):"مسودة"}</b></div><div><span>رقم العميل</span><b className="numeric">{sequenceNumber(customer.code)}</b></div><div><span>اسم العميل</span><b>{customer.name}</b></div><div><span>رقم الجوال</span><b className="numeric">{customer.phone}</b></div><div><span>عدد الثياب</span><b className="numeric">{numberFormat.format(thobes.length)}</b></div><div><span>تاريخ التفصيل</span><b className="numeric">{invoice?shortDateFormat.format(databaseDate(invoice.createdAt)):shortDateFormat.format(new Date())}</b></div><div><span>تاريخ التسليم</span><b className="numeric">{deliveryDate||"—"}</b></div><hr/><section className="receipt-thobes">{thobes.map((thobe,index)=><p key={index}><b>الثوب <span className="numeric">{index+1}</span></b><span>{thobe.thobeType} · {thobe.sleeveMode} · {thobe.designs[thobe.collarMode==="قلاب"?"القلاب":"الرقبة السادة"]?.name||thobe.collarMode}</span></p>)}</section><hr/><div><span>الإجمالي</span><b className="numeric">{numberFormat.format(total)} ر.س</b></div><div><span>المدفوع — {paymentMethod}</span><b className="numeric">{numberFormat.format(paid)} ر.س</b></div><div><span>الخصم</span><b className="numeric">{numberFormat.format(discount)} ر.س</b></div><div className="receipt-total"><span>المتبقي</span><b className="numeric">{numberFormat.format(remaining)} ر.س</b></div><hr/><small>شكرًا لاختياركم أناقة التميز</small></article>}

function LaundryReceiptSheet({customer,invoice,thobe,index,total,deliveryDate}:{customer:Customer;invoice:InvoiceRecord|null;thobe:ThobeDraft;index:number;total:number;deliveryDate:string}){const collarCategory=thobe.collarMode==="قلاب"?"القلاب":"الرقبة السادة",collarName=thobe.designs[collarCategory]?.name||thobe.collarMode;return <article className="paper receipt-paper laundry-receipt" dir="rtl"><h2>أناقة التميز</h2><p>بطاقة المغسلة</p><hr/><div><span>رقم الفاتورة</span><b className="numeric">{invoice?sequenceNumber(invoice.invoiceNumber):"مسودة"}</b></div><div><span>رقم العميل</span><b className="numeric">{sequenceNumber(customer.code)}</b></div><div><span>اسم العميل</span><b>{customer.name}</b></div><div><span>الثوب</span><b className="numeric">{index+1} / {total}</b></div><div><span>نوع الثوب</span><b>{thobe.thobeType}</b></div><hr/><div><span>نوع الرقبة</span><b>{collarName}</b></div><div><span>محيط الرقبة</span><b className="numeric">{thobe.measurements["محيط الرقبة"]||"—"}</b></div>{thobe.collarMode==="قلاب"?<div><span>مقاس القلاب</span><b className="numeric">{thobe.measurements["مقاس القلاب الأول"]||"—"} — {thobe.measurements["مقاس القلاب الثاني"]||"—"}</b></div>:<div><span>مقاس الرقبة السادة</span><b className="numeric">{thobe.measurements["مقاس الرقبة السادة"]||"—"}</b></div>}<div><span>عدد أزرار الرقبة</span><b className="numeric">{thobe.neckButtonCount}</b></div><div><span>نوع أزرار الرقبة</span><b>{thobe.neckButtonType}</b></div><div><span>نوع اليد</span><b>{thobe.sleeveMode}</b></div><div><span>تاريخ التسليم</span><b className="numeric">{deliveryDate||"—"}</b></div>{thobe.notes&&<><hr/><p className="laundry-note">ملاحظة: {thobe.notes}</p></>}<hr/><small>الثوب <span className="numeric">{index+1}</span> من <span className="numeric">{total}</span></small></article>}

export default function App(){
  const [view,setView]=useState<View>("dashboard");const [data,setData]=useState<Dashboard|null>(null);const [workItems,setWorkItems]=useState<WorkBoardItem[]>([]);const [workQueries,setWorkQueries]=useState<Record<string,string>>({});const [movingOrder,setMovingOrder]=useState<number|null>(null);const [session,setSession]=useState<CurrentSession|null>(null);const [history,setHistory]=useState<SessionEntry[]>([]);const [historyOpen,setHistoryOpen]=useState(false);const [selectedDay,setSelectedDay]=useState("");const [now,setNow]=useState(Date.now());const [error,setError]=useState("");
  const [customerName,setCustomerName]=useState("");const [customerPhone,setCustomerPhone]=useState("");const [customerError,setCustomerError]=useState("");const [savingCustomer,setSavingCustomer]=useState(false);const [currentCustomer,setCurrentCustomer]=useState<Customer|null>(null);
  const [customerQuery,setCustomerQuery]=useState("");const [customerResults,setCustomerResults]=useState<CustomerSearchItem[]>([]);const [selectedCustomer,setSelectedCustomer]=useState<CustomerSearchItem|null>(null);const [customerInvoices,setCustomerInvoices]=useState<SavedInvoice[]>([]);const [customerSearchBusy,setCustomerSearchBusy]=useState(false);const [customerHistoryBusy,setCustomerHistoryBusy]=useState(false);const [customerSearchMessage,setCustomerSearchMessage]=useState("");const [orderReturnView,setOrderReturnView]=useState<"dashboard"|"customers">("dashboard");
  const customerSearchRequest=useRef(0);
  const [designOptions,setDesignOptions]=useState<DesignOption[]>([]);const [settingsCategory,setSettingsCategory]=useState(defaultCategories[0]);const [optionName,setOptionName]=useState("");const [optionImage,setOptionImage]=useState("");const [settingsError,setSettingsError]=useState("");const [pickerCategory,setPickerCategory]=useState<string|null>(null);const [selectedDesigns,setSelectedDesigns]=useState<Record<string,DesignOption|undefined>>({});
  const [measurements,setMeasurements]=useState<Record<string,string>>(()=>blankFields(measurementFields));const [fabric,setFabric]=useState<Record<string,string>>(()=>blankFields(fabricFields));const [unit,setUnit]=useState<"سم"|"إنش">("سم");const [weight,setWeight]=useState("");const [deliveryDate,setDeliveryDate]=useState(()=>deliveryAfter(5));const [dayCount,setDayCount]=useState("5");const [totalThobes,setTotalThobes]=useState("1");const [thobeType,setThobeType]=useState("سعودي");const [sleeveMode,setSleeveMode]=useState<SleeveMode>("سادة");const [collarMode,setCollarMode]=useState<CollarMode>("قلاب");const [neckButtonCount,setNeckButtonCount]=useState<"1"|"2">("1");const [neckButtonType,setNeckButtonType]=useState<NeckButtonType>("طقطق");const [notes,setNotes]=useState("");const [thobeDrafts,setThobeDrafts]=useState<ThobeDraft[]>(()=>[blankThobe()]);const [currentThobe,setCurrentThobe]=useState(0);
  const [totalPrice,setTotalPrice]=useState("");const [paidAmount,setPaidAmount]=useState("");const [discount,setDiscount]=useState("");const [paymentMethod,setPaymentMethod]=useState("كاش");const [invoice,setInvoice]=useState<InvoiceRecord|null>(null);const [orderLocked,setOrderLocked]=useState(false);const [savingInvoice,setSavingInvoice]=useState(false);const [orderMessage,setOrderMessage]=useState("");const [previewTarget,setPreviewTarget]=useState<PrintTarget|null>(null);
  const [storage,setStorage]=useState<StorageInfo|null>(null);const [storageBusy,setStorageBusy]=useState(false);const [storageMessage,setStorageMessage]=useState("");
  const total=numericValue(totalPrice),paid=numericValue(paidAmount),discountValue=numericValue(discount),remaining=Math.max(0,total-paid-discountValue);const categories=useMemo(()=>Array.from(new Set([...defaultCategories,...designOptions.map(option=>option.category)])),[designOptions]);

  async function load(){try{setError("");const [dashboard,current,board]=await Promise.all([invoke<Dashboard>("dashboard_summary"),invoke<CurrentSession>("current_session"),invoke<WorkBoardItem[]>("work_board")]);setData(dashboard);setSession(current);setWorkItems(board)}catch{setError("تعذر قراءة بيانات المحل المحلية.")}}
  async function loadDesignOptions(){try{setDesignOptions(await invoke<DesignOption[]>("list_design_options"))}catch{setSettingsError("تعذر قراءة مكتبة الأشكال.")}}
  async function loadStorageInfo(){try{setStorage(await invoke<StorageInfo>("storage_info"))}catch{setStorageMessage("تعذر قراءة مكان حفظ البيانات.")}}
  async function showHistory(){setHistoryOpen(true);try{setHistory(await invoke<SessionEntry[]>("session_history"))}catch{setError("تعذر قراءة سجل التشغيل.")}}
  async function advanceWorkItem(orderId:number){try{setMovingOrder(orderId);setError("");await invoke("advance_order_status",{orderId});await load()}catch{setError("تعذر نقل الثوب إلى المرحلة التالية.")}finally{setMovingOrder(null)}}
  async function retreatWorkItem(orderId:number){try{setMovingOrder(orderId);setError("");await invoke("retreat_order_status",{orderId});await load()}catch{setError("تعذر إرجاع الثوب إلى المرحلة السابقة.")}finally{setMovingOrder(null)}}
  useEffect(()=>{void load();void loadDesignOptions();void loadStorageInfo();const interval=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(interval)},[]);
  useEffect(()=>{if(view!=="customers")return;const timer=window.setTimeout(()=>void searchCustomerRecords(customerQuery),180);return()=>window.clearTimeout(timer)},[customerQuery,view]);
  function closeCustomer(){setCustomerName("");setCustomerPhone("");setCustomerError("");setView("dashboard")}
  async function saveCustomer(event:FormEvent<HTMLFormElement>){event.preventDefault();const name=customerName.trim(),phone=latinDigits(customerPhone).trim();if(!name){setCustomerError("اكتب اسم العميل.");return}if(phone.replace(/\D/g,"").length<7){setCustomerError("اكتب رقم جوال صحيحًا بالأرقام الإنجليزية.");return}try{setSavingCustomer(true);setCustomerError("");const customer=await invoke<Customer>("create_customer",{name,phone});setCurrentCustomer(customer);setOrderReturnView("dashboard");resetInvoice();setView("order")}catch{setCustomerError("تعذر حفظ العميل. حاول مرة أخرى.")}finally{setSavingCustomer(false)}}
  async function searchCustomerRecords(query=customerQuery){
    const request=++customerSearchRequest.current;
    try{setCustomerSearchBusy(true);setCustomerSearchMessage("");const results=await invoke<CustomerSearchItem[]>("search_customers",{query:query.trim()});if(request===customerSearchRequest.current)setCustomerResults(results)}
    catch{if(request===customerSearchRequest.current){setCustomerSearchMessage("تعذر البحث في بيانات العملاء.");setCustomerResults([])}}finally{if(request===customerSearchRequest.current)setCustomerSearchBusy(false)}
  }
  function openCustomerSearch(){setCustomerQuery("");setSelectedCustomer(null);setCustomerInvoices([]);setCustomerSearchMessage("");setView("customers")}
  async function selectCustomerRecord(customer:CustomerSearchItem){
    setSelectedCustomer(customer);setCustomerInvoices([]);setCustomerSearchMessage("");
    try{setCustomerHistoryBusy(true);setCustomerInvoices(await invoke<SavedInvoice[]>("customer_invoices",{customerId:customer.id}))}
    catch{setCustomerSearchMessage("تعذر قراءة فواتير هذا العميل.")}finally{setCustomerHistoryBusy(false)}
  }
  function draftsFromInvoice(saved:SavedInvoice){
    const details=parseObject(saved.detailsJson);
    const rawThobes=Array.isArray(details.thobes)?details.thobes:[];
    const legacy={measurements:parseObject(saved.measurementsJson),fabric:parseObject(saved.fabricJson),designs:parseObject(saved.designsJson),thobeType:details.thobeType,sleeveMode:details.sleeveMode,collarMode:details.collarMode,neckButtonCount:details.neckButtonCount,neckButtonType:details.neckButtonType,notes:saved.notes};
    const sources=rawThobes.length?rawThobes:[legacy];
    const drafts=sources.map(source=>{
      const raw=objectValue(source),designs:Record<string,DesignOption|undefined>={},storedMeasurements=textRecord(raw.measurements);
      if(!storedMeasurements["طول الكبك"]&&storedMeasurements["طول الكباك"])storedMeasurements["طول الكبك"]=storedMeasurements["طول الكباك"];
      if(!storedMeasurements["عرض الكبك"]&&storedMeasurements["عرض الكباك"])storedMeasurements["عرض الكبك"]=storedMeasurements["عرض الكباك"];
      Object.entries(objectValue(raw.designs)).forEach(([category,id])=>{const normalizedCategory=category==="الكباك"?"الكبك":category,option=designOptions.find(item=>item.id===Number(id));if(option)designs[normalizedCategory]=option});
      const sleeve: SleeveMode=raw.sleeveMode==="كبك"||raw.sleeveMode==="كباك"?"كبك":"سادة";
      const collar: CollarMode=raw.collarMode==="سادة"?"سادة":"قلاب";
      const buttonCount:"1"|"2"=String(raw.neckButtonCount)==="2"?"2":"1",buttonType:NeckButtonType=raw.neckButtonType==="بلاستيك"?"بلاستيك":"طقطق";
      return {measurements:{...blankFields(measurementFields),...storedMeasurements},fabric:{...blankFields(fabricFields),...textRecord(raw.fabric)},designs,thobeType:String(raw.thobeType||"سعودي"),sleeveMode:sleeve,collarMode:collar,neckButtonCount:buttonCount,neckButtonType:buttonType,notes:String(raw.notes??saved.notes??"")} satisfies ThobeDraft;
    });
    while(drafts.length<Math.max(1,saved.totalThobes))drafts.push(cloneThobe(drafts[0]));
    return {drafts,unit:details.unit==="إنش"?"إنش" as const:"سم" as const};
  }
  function startBlankInvoice(customer:CustomerSearchItem){setCurrentCustomer({id:customer.id,code:customer.code,name:customer.name,phone:customer.phone});setOrderReturnView("customers");resetInvoice();setView("order")}
  function openCustomerInvoice(saved:SavedInvoice,duplicate:boolean){
    if(!selectedCustomer)return;
    const {drafts,unit:storedUnit}=draftsFromInvoice(saved),customer={id:selectedCustomer.id,code:selectedCustomer.code,name:selectedCustomer.name,phone:selectedCustomer.phone};
    setCurrentCustomer(customer);setOrderReturnView("customers");setThobeDrafts(drafts);setCurrentThobe(0);applyThobe(drafts[0]);setUnit(storedUnit);setWeight(saved.weight);setTotalThobes(String(drafts.length));
    if(duplicate){setDeliveryDate(deliveryAfter(5));setDayCount("5");setTotalPrice("");setPaidAmount("");setDiscount("");setPaymentMethod("كاش");setInvoice(null);setOrderLocked(false);setOrderMessage(`تم نسخ مقاسات الفاتورة ${sequenceNumber(saved.invoiceNumber)} إلى فاتورة جديدة`)}
    else{setDeliveryDate(saved.deliveryDate);setDayCount(String(saved.dayCount));setTotalPrice(saved.totalPrice);setPaidAmount(saved.paidAmount);setDiscount(saved.discount);setPaymentMethod(saved.paymentMethod||"كاش");setInvoice({id:saved.id,invoiceNumber:saved.invoiceNumber,createdAt:saved.createdAt});setOrderLocked(true);setOrderMessage(`تم فتح الفاتورة المحفوظة ${sequenceNumber(saved.invoiceNumber)}`)}
    setView("order");
  }
  function captureThobe():ThobeDraft{return {measurements:{...measurements},fabric:{...fabric},designs:{...selectedDesigns},thobeType,sleeveMode,collarMode,neckButtonCount,neckButtonType,notes}}
  function applyThobe(thobe:ThobeDraft){setMeasurements({...thobe.measurements});setFabric({...thobe.fabric});setSelectedDesigns({...thobe.designs});setThobeType(thobe.thobeType);setSleeveMode(thobe.sleeveMode);setCollarMode(thobe.collarMode);setNeckButtonCount(thobe.neckButtonCount);setNeckButtonType(thobe.neckButtonType);setNotes(thobe.notes)}
  function completeThobeDrafts(count=Math.max(1,Number(totalThobes)||1)){const next=Array.from({length:count},(_,index)=>thobeDrafts[index]?cloneThobe(thobeDrafts[index]):blankThobe());if(currentThobe<count)next[currentThobe]=captureThobe();return next}
  function resetInvoice(){const first=blankThobe();applyThobe(first);setThobeDrafts([first]);setCurrentThobe(0);setWeight("");setDeliveryDate(deliveryAfter(5));setDayCount("5");setTotalThobes("1");setTotalPrice("");setPaidAmount("");setDiscount("");setPaymentMethod("كاش");setInvoice(null);setOrderLocked(false);setOrderMessage("")}
  function changeDeliveryDate(value:string){setDeliveryDate(value);if(!value){setDayCount("0");return}const delivery=new Date(`${value}T00:00:00`),todayDate=new Date();todayDate.setHours(0,0,0,0);setDayCount(String(Math.max(0,Math.ceil((delivery.getTime()-todayDate.getTime())/86400000))))}
  function changeDayCount(value:string){const normalized=latinDigits(value).replace(/[^0-9]/g,"");setDayCount(normalized);if(normalized===""){setDeliveryDate("");return}const delivery=new Date();delivery.setHours(0,0,0,0);delivery.setDate(delivery.getDate()+Number(normalized));setDeliveryDate(dateInputValue(delivery))}
  function changeTotalThobes(value:string){const count=Math.min(20,Math.max(1,Number(latinDigits(value).replace(/[^0-9]/g,""))||1));const next=completeThobeDrafts(count);const target=Math.min(currentThobe,count-1);setTotalThobes(String(count));setThobeDrafts(next);if(target!==currentThobe){setCurrentThobe(target);applyThobe(next[target])}}
  function switchThobe(index:number){if(index===currentThobe)return;const next=completeThobeDrafts();setThobeDrafts(next);setCurrentThobe(index);applyThobe(next[index]||blankThobe());setOrderMessage("")}
  function copyPreviousThobe(){if(currentThobe===0)return;const next=completeThobeDrafts();const copied=cloneThobe(next[currentThobe-1]);next[currentThobe]=copied;setThobeDrafts(next);applyThobe(copied);setOrderMessage(`تم نسخ مقاسات الثوب ${currentThobe}`)}
  async function saveInvoice():Promise<boolean>{if(!currentCustomer)return false;try{setSavingInvoice(true);setOrderMessage("");const drafts=completeThobeDrafts();setThobeDrafts(drafts);const first=drafts[0];const storedThobes=drafts.map(thobe=>({...thobe,designs:Object.fromEntries(Object.entries(thobe.designs).map(([category,option])=>[category,option?.id??null]))}));const record=await invoke<InvoiceRecord>("save_invoice",{payload:{id:invoice?.id??null,customerId:currentCustomer.id,weight,deliveryDate,dayCount:Number(dayCount)||0,totalThobes:drafts.length,totalPrice,paidAmount,paymentMethod,discount,notes:first.notes,measurementsJson:JSON.stringify(first.measurements),fabricJson:JSON.stringify(first.fabric),designsJson:JSON.stringify(Object.fromEntries(Object.entries(first.designs).map(([category,option])=>[category,option?.id]))),detailsJson:JSON.stringify({thobeType:first.thobeType,unit,sleeveMode:first.sleeveMode,collarMode:first.collarMode,neckButtonCount:first.neckButtonCount,neckButtonType:first.neckButtonType,thobes:storedThobes})}});setInvoice(record);setOrderLocked(true);setOrderMessage(`تم حفظ الفاتورة ${record.invoiceNumber}`);return true}catch{setOrderMessage("تعذر حفظ الفاتورة.");return false}finally{setSavingInvoice(false)}}
  function exitWithoutSave(){const destination=orderReturnView;setCurrentCustomer(null);resetInvoice();setView(destination)}
  async function saveAndExit(){if(!orderLocked){const saved=await saveInvoice();if(!saved)return}const destination=orderReturnView;setCurrentCustomer(null);setView(destination);await load();if(destination==="customers"){await searchCustomerRecords(customerQuery);if(selectedCustomer)await selectCustomerRecord(selectedCustomer)}}
  async function ensureInvoiceSaved(){if(invoice&&orderLocked)return true;return saveInvoice()}
  async function openPrintPreview(target:PrintTarget){if(await ensureInvoiceSaved())setPreviewTarget(target)}
  async function selectImage(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;try{setOptionImage(await imageFromFile(file));setSettingsError("")}catch{setSettingsError("تعذر قراءة الصورة.")}}
  async function addDesignOption(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!settingsCategory.trim()||!optionName.trim()||!optionImage){setSettingsError("اكتب اسم النوع واختر صورته.");return}try{await invoke("add_design_option",{category:settingsCategory.trim(),name:optionName.trim(),imageData:optionImage});setOptionName("");setOptionImage("");setSettingsError("");await loadDesignOptions()}catch{setSettingsError("تعذر حفظ النوع والصورة.")}}
  async function chooseStorage(mode:"copy"|"use"){
    if(currentCustomer){setStorageMessage("اخرج من فاتورة العميل أولًا، ثم غيّر مكان البيانات من الإعدادات.");return}
    const selected=await open({directory:true,multiple:false,title:mode==="copy"?"اختر مجلدًا فارغًا لنسخ بيانات TAILOR":"اختر المجلد الذي يحتوي على tailor.sqlite"});
    if(typeof selected!=="string")return;
    try{
      setStorageBusy(true);setStorageMessage("");
      const next=await invoke<StorageInfo>("set_storage_location",{folder:selected,mode});
      setStorage(next);
      setStorageMessage(mode==="copy"?"تم نسخ جميع البيانات واستخدام المجلد الجديد.":"تم ربط قاعدة البيانات الموجودة وتحميلها.");
      await Promise.all([load(),loadDesignOptions()]);
    }catch(error){setStorageMessage(String(error))}finally{setStorageBusy(false)}
  }
  async function deleteDesignOption(id:number){try{await invoke("delete_design_option",{id});setSelectedDesigns(current=>Object.fromEntries(Object.entries(current).filter(([,option])=>option?.id!==id)));await loadDesignOptions()}catch{setSettingsError("تعذر حذف النوع.")}}
  function printSheet(target:PrintTarget){setPreviewTarget(null);document.body.dataset.printTarget=target;window.setTimeout(()=>{window.print();window.setTimeout(()=>delete document.body.dataset.printTarget,500)},100)}
  function measurementInput(field:string){return <label className="compact-field" key={field}><span>{field}</span><div><input className="numeric" disabled={orderLocked} value={measurements[field]||""} onChange={event=>setMeasurements(current=>({...current,[field]:latinDigits(event.target.value)}))} placeholder="—"/><small>{unit}</small></div></label>}
  function bodyLengthInput(){return <label className="compact-field body-length-field"><span>الطول</span><div className="named-dual-measure"><label><em>أمام</em><input className="numeric" disabled={orderLocked} value={measurements["طول أمام"]||""} onChange={event=>setMeasurements(current=>({...current,"طول أمام":latinDigits(event.target.value)}))} placeholder="—"/></label><label><em>خلف</em><input className="numeric" disabled={orderLocked} value={measurements["طول خلف"]||""} onChange={event=>setMeasurements(current=>({...current,"طول خلف":latinDigits(event.target.value)}))} placeholder="—"/></label><small>{unit}</small></div></label>}
  function photoPicker(category:string,label:string){const option=selectedDesigns[category];return <button className={`compact-photo ${option?"chosen":""}`} type="button" disabled={orderLocked} onClick={()=>setPickerCategory(category)}>{option?<img src={option.imageData} alt={option.name}/>:<span>＋</span>}<b>{option?.name||label}</b></button>}
  function changeThobeType(value:string){setThobeType(value);const option=designOptions.find(item=>item.category==="نوع الثوب"&&item.name===value);setSelectedDesigns(current=>({...current,"نوع الثوب":option}))}
  function changeSleeveMode(mode:"سادة"|"كبك"){setSleeveMode(mode);setMeasurements(current=>({...current,...(mode==="سادة"?{"طول الكبك":"","عرض الكبك":""}:{"الخبنة":""})}));setSelectedDesigns(current=>({...current,[mode==="سادة"?"الكبك":"اليد السادة"]:undefined}))}
  function changeCollarMode(mode:"قلاب"|"سادة"){setCollarMode(mode);setMeasurements(current=>({...current,...(mode==="قلاب"?{"مقاس الرقبة السادة":""}:{"مقاس القلاب الأول":"","مقاس القلاب الثاني":""})}));setSelectedDesigns(current=>({...current,[mode==="قلاب"?"الرقبة السادة":"القلاب"]:undefined}))}

  const today=new Date(),started=session?databaseDate(session.startedAt):null,elapsed=started?durationLabel(now-started.getTime()):"—";
  const displayHistory=useMemo<DisplaySession[]>(()=>{const saved=history.map((item,index)=>({start:databaseDate(item.startedAt),end:databaseDate(item.endedAt),active:false,key:`${item.startedAt}-${index}`}));if(started)saved.unshift({start:started,end:new Date(now),active:true,key:`active-${session?.startedAt}`});return saved},[history,now,session?.startedAt,started]);const filteredHistory=selectedDay?displayHistory.filter(item=>dayKey(item.start)===selectedDay):displayHistory;
  const outputDrafts=completeThobeDrafts();const allThobesMatch=outputDrafts.every(thobe=>comparableThobe(thobe)===comparableThobe(outputDrafts[0]));
  const measurementSheets:SheetProps[]=currentCustomer?(allThobesMatch?[{customer:currentCustomer,invoice,weight,deliveryDate,totalThobes:String(outputDrafts.length),...outputDrafts[0],sheetLabel:outputDrafts.length>1?`مقاس موحد لعدد ${outputDrafts.length}`:undefined}]:outputDrafts.map((thobe,index)=>({customer:currentCustomer,invoice,weight,deliveryDate,totalThobes:"1",...thobe,sheetLabel:`الثوب ${index+1} من ${outputDrafts.length}`}))):[];
  const previewTitle=previewTarget==="measurements"?`معاينة طباعة المقاس — ${measurementSheets.length} ورقة A5`:previewTarget==="receipt"?"معاينة فاتورة السعر للعميل":`معاينة فواتير المغسلة — ${outputDrafts.length} فاتورة`;

  return <main className="app-shell"><header className="topbar"><div className="brand"><span>ت</span><div><strong>TAILOR</strong><small>إدارة التفصيل</small></div></div><div className="top-actions"><button type="button" onClick={()=>setView("settings")}>⚙ <span>الإعدادات</span></button><time className="numeric">{dateFormat.format(today)}</time></div></header>
    {view==="dashboard"&&<div className="workspace">
      <aside className="side-menu side-right"><p className="side-label">القائمة الرئيسية</p><div className="side-cards">{rightMenu.map(([label,icon],index)=><MenuCard key={label} label={label} icon={icon} onSelect={index===0?()=>setView("add-customer"):index===1?openCustomerSearch:undefined}/>)}</div></aside>
      <section className="dashboard">
        <section className="greeting"><span>مساحة العمل</span><h1>مرحباً بك</h1><p>هذه نظرة اليوم على حركة التفصيل والتسليم.</p><time className="numeric">{dateFormat.format(today)}</time></section>
        <section className="metric-grid" aria-live="polite"><article className="metric-card received"><span className="metric-icon">↓</span><p>القبض</p><strong className="numeric">{data?numberFormat.format(data.receivedToday):"—"}</strong></article><article className="metric-card tailored"><span className="metric-icon">✦</span><p>تم تفصيلها اليوم</p><strong className="numeric">{data?numberFormat.format(data.tailoredToday):"—"}</strong></article><article className="metric-card due"><span className="metric-icon">◷</span><p>جاهزة للتسليم</p><strong className="numeric">{data?numberFormat.format(data.readyToDeliver):"—"}</strong></article></section>
        <section className="work-board" aria-label="مراحل العمل على الثياب">{workStatuses.map((status,index)=>{const items=workItems.filter(item=>item.status===status),query=normalizedArabic(workQueries[status]||""),visibleItems=query?items.filter(item=>normalizedArabic(item.customerName).includes(query)):items;return <article className="work-board-column" key={status}><header><h2>{status}</h2><b className="numeric">{numberFormat.format(items.reduce((sum,item)=>sum+item.quantity,0))}</b></header><label className="work-board-search"><span aria-hidden="true">⌕</span><input value={workQueries[status]||""} onChange={event=>setWorkQueries(current=>({...current,[status]:event.target.value}))} placeholder="ابحث باسم الزبون" aria-label={`البحث باسم الزبون في ${status}`}/></label><div>{visibleItems.length===0&&<p>{query?"لا يوجد زبون مطابق":"لا توجد ثياب"}</p>}{visibleItems.map(item=><section className="work-board-item" key={item.orderId}><span><strong>{item.customerName}</strong><small>عميل <b className="numeric">{sequenceNumber(item.customerCode)}</b> · فاتورة <b className="numeric">{sequenceNumber(item.invoiceNumber)}</b> · <b className="numeric">{numberFormat.format(item.quantity)}</b> ثوب</small></span><span className="work-board-actions">{index<workStatuses.length-1&&<button className="advance" type="button" disabled={movingOrder===item.orderId} onClick={()=>void advanceWorkItem(item.orderId)} title={`نقل إلى ${workStatuses[index+1]}`} aria-label={`نقل ${item.customerName} إلى ${workStatuses[index+1]}`}>←</button>}{index>0&&<button className="retreat" type="button" disabled={movingOrder===item.orderId} onClick={()=>void retreatWorkItem(item.orderId)} title={`رجوع إلى ${workStatuses[index-1]}`} aria-label={`إرجاع ${item.customerName} إلى ${workStatuses[index-1]}`}>→</button>}</span></section>)}</div></article>})}</section>
        <button className="session-card" type="button" onClick={()=>void showHistory()}><span className="session-heading"><strong className="session-kicker">سجل تشغيل التطبيق</strong><small>اضغط لعرض الأيام السابقة</small></span><span className="session-dates"><strong className="numeric">{dateFormat.format(today)}</strong><small className="numeric">هجريًا: {hijriDateFormat.format(today)}</small></span><span className="session-runtime"><span><small>فُتح التطبيق عند</small><strong className="numeric">{started?timeFormat.format(started):"—"}</strong></span><span><small>مدة التشغيل الحالية</small><b className="numeric">{elapsed}</b></span></span><span className="session-action">عرض السجل ←</span></button>
        {error&&<p className="error">{error}</p>}
      </section>
      <aside className="side-menu side-left"><p className="side-label">متابعة المحل</p><div className="side-cards">{leftMenu.map(([label,icon])=><MenuCard key={label} label={label} icon={icon}/>)}</div></aside>
    </div>}
    {view==="add-customer"&&<section className="customer-workspace" dir="rtl"><div className="customer-page-head"><button className="page-close" type="button" onClick={closeCustomer} aria-label="إغلاق بدون حفظ">×</button><span>العملاء</span><h1>إضافة عميل جديد</h1><p>أدخل البيانات الأساسية للعميل، ثم احفظ للانتقال إلى فاتورته الجديدة.</p></div><form className="customer-form" onSubmit={event=>void saveCustomer(event)}><div className="customer-fields"><label><span>اسم العميل</span><input autoFocus value={customerName} onChange={event=>setCustomerName(event.target.value)} placeholder="اكتب الاسم الكامل" autoComplete="name"/></label><label><span>رقم الجوال</span><input className="numeric" type="tel" inputMode="numeric" dir="ltr" value={customerPhone} onChange={event=>setCustomerPhone(latinDigits(event.target.value).replace(/[^0-9+ -]/g,""))} placeholder="05XXXXXXXX" autoComplete="tel"/></label></div>{customerError&&<p className="customer-error" role="alert">{customerError}</p>}<div className="customer-actions"><button className="save-customer" type="submit" disabled={savingCustomer}>{savingCustomer?"جارٍ الحفظ…":"حفظ ومتابعة"}</button><button className="clear-customer" type="button" onClick={()=>{setCustomerName("");setCustomerPhone("");setCustomerError("")}}>مسح المدخلات</button><button className="cancel-customer" type="button" onClick={closeCustomer}>إغلاق بدون حفظ</button></div></form></section>}
    {view==="customers"&&<section className="customer-search-page" dir="rtl">
      <header className="customer-search-head"><div><span>العملاء</span><h1>بحث عن عميل</h1><p>ابحث بالاسم أو رقم العميل أو رقم الجوال، ثم اختر العميل لعرض جميع فواتيره السابقة.</p></div><button type="button" onClick={()=>setView("dashboard")}>رجوع للرئيسية</button></header>
      <div className="customer-search-layout">
        <aside className="customer-results-panel">
          <form className="customer-search-form" onSubmit={event=>{event.preventDefault();void searchCustomerRecords()}}><label><span>البحث عن العميل باسمه أو رقمه</span><div><input autoFocus value={customerQuery} onChange={event=>{setCustomerQuery(event.target.value);setSelectedCustomer(null);setCustomerInvoices([])}} placeholder="الاسم، رقم العميل أو الجوال"/><button type="submit" disabled={customerSearchBusy}>{customerSearchBusy?"جارٍ البحث…":"بحث"}</button></div></label></form>
          <div className="customer-table-head"><b>بيانات العميل</b><b>رقم العميل</b></div>
          <div className="customer-result-list">{!customerSearchBusy&&customerResults.length===0&&<p className="customer-empty">لا يوجد عميل مطابق للبحث.</p>}{customerResults.map(customer=><button type="button" className={selectedCustomer?.id===customer.id?"selected":""} key={customer.id} onClick={()=>void selectCustomerRecord(customer)}><span className="customer-result-data"><strong>{customer.name}</strong><small className="numeric">{customer.phone}</small><em>عدد الفواتير: <b className="numeric">{numberFormat.format(customer.invoiceCount)}</b></em></span><span className="customer-result-number numeric">{sequenceNumber(customer.code)}</span></button>)}</div>
        </aside>
        <section className="customer-history-panel">
          {!selectedCustomer&&<div className="customer-history-placeholder"><span>⌕</span><h2>اختر عميلًا من القائمة</h2><p>ستظهر هنا كل فاتورة سابقة في سطر مستقل، دون خلطها أو الكتابة فوقها.</p></div>}
          {selectedCustomer&&<><header className="selected-customer-head"><div><span>سجل العميل</span><h2>{selectedCustomer.name}</h2><p><b className="numeric">رقم العميل: {sequenceNumber(selectedCustomer.code)}</b><b className="numeric">الجوال: {selectedCustomer.phone}</b></p></div><button type="button" onClick={()=>startBlankInvoice(selectedCustomer)}>فاتورة جديدة فارغة</button></header>
          <div className="invoice-history-list">{customerHistoryBusy&&<p className="customer-empty">جارٍ قراءة فواتير العميل…</p>}{!customerHistoryBusy&&customerInvoices.length===0&&<div className="customer-history-placeholder small"><h3>لا توجد فواتير سابقة لهذا العميل</h3><p>يمكنك إنشاء أول فاتورة له من الزر الموجود بالأعلى.</p></div>}{customerInvoices.map(saved=>{const savedRemaining=Math.max(0,numericValue(saved.totalPrice)-numericValue(saved.paidAmount)-numericValue(saved.discount));return <article className="invoice-history-row" key={saved.id}><div className="invoice-history-number"><small>رقم الفاتورة</small><strong className="numeric">{sequenceNumber(saved.invoiceNumber)}</strong></div><div className="invoice-history-data"><h3>تفصيل بتاريخ <span className="numeric">{shortDateFormat.format(databaseDate(saved.createdAt))}</span></h3><p><span>عدد الثياب: <b className="numeric">{numberFormat.format(saved.totalThobes)}</b></span><span>تاريخ التسليم: <b className="numeric">{saved.deliveryDate||"—"}</b></span><span>المتبقي: <b className="numeric">{numberFormat.format(savedRemaining)} ر.س</b></span></p></div><div className="invoice-history-actions"><button type="button" onClick={()=>openCustomerInvoice(saved,false)}>فتح</button><button className="duplicate-invoice" type="button" onClick={()=>openCustomerInvoice(saved,true)}>فاتورة جديدة بنفس المقاسات</button></div></article>})}</div></>}
          {customerSearchMessage&&<p className="customer-search-message" role="alert">{customerSearchMessage}</p>}
        </section>
      </div>
    </section>}
    {view==="order"&&currentCustomer&&<section className="order-page compact-order" dir="rtl">
      <div className="compact-order-head"><div><span>{invoice?"فاتورة محفوظة":"فاتورة جديدة"}</span><h1>مقاسات الثوب</h1></div><div className="compact-head-actions"><div className="unit-switch"><button type="button" className={unit==="سم"?"selected":""} disabled={orderLocked} onClick={()=>setUnit("سم")}>سم</button><button type="button" className={unit==="إنش"?"selected":""} disabled={orderLocked} onClick={()=>setUnit("إنش")}>إنش</button></div><button type="button" onClick={()=>setView("settings")}>إدارة الصور</button><button className="save-exit" type="button" disabled={savingInvoice} onClick={()=>void saveAndExit()}>{orderLocked?"تم الحفظ — خروج":"حفظ وخروج"}</button><button className="discard-exit" type="button" onClick={exitWithoutSave}>خروج بدون حفظ</button></div></div>

      <section className="order-summary-strip">
        <div><span>اسم العميل</span><b>{currentCustomer.name}</b></div>
        <div><span>رقم الجوال</span><b className="numeric">{currentCustomer.phone}</b></div>
        <div><span>رقم العميل</span><b className="numeric">{sequenceNumber(currentCustomer.code)}</b></div>
        <label><span>الوزن</span><input className="numeric" disabled={orderLocked} value={weight} onChange={event=>setWeight(latinDigits(event.target.value))} placeholder="—"/></label>
        <div><span>رقم الفاتورة</span><b className="numeric">{invoice?sequenceNumber(invoice.invoiceNumber):"عند الحفظ"}</b></div>
        <div><span>تاريخ التفصيل</span><b className="numeric">{invoice?`${shortDateFormat.format(databaseDate(invoice.createdAt))} ${timeFormat.format(databaseDate(invoice.createdAt))}`:`${shortDateFormat.format(today)} ${timeFormat.format(today)}`}</b></div>
        <label><span>أيام العمل</span><input className="numeric" inputMode="numeric" disabled={orderLocked} value={dayCount} onChange={event=>changeDayCount(event.target.value)}/></label>
        <label><span>تاريخ التسليم</span><input className="numeric" type="date" disabled={orderLocked} value={deliveryDate} onChange={event=>changeDeliveryDate(event.target.value)}/></label>
        <label><span>عدد الثياب</span><input className="numeric" inputMode="numeric" disabled={orderLocked} value={totalThobes} onChange={event=>changeTotalThobes(event.target.value)}/></label>
      </section>

      <nav className="thobe-steps" aria-label="الثياب في الفاتورة"><span>الثوب الحالي</span>{outputDrafts.map((_,index)=><button type="button" key={index} className={currentThobe===index?"selected":""} onClick={()=>switchThobe(index)}>الثوب <b className="numeric">{index+1}</b></button>)}{currentThobe>0&&!orderLocked&&<button className="copy-step" type="button" onClick={copyPreviousThobe}>نسخ مقاسات الثوب السابق</button>}</nav>

      <section className="measure-columns">
        <article className="measure-column body-column"><header><span>01</span><h2>الثوب والجسم</h2></header>{photoPicker("نوع الثوب","أضف صورة نوع الثوب")}<label className="compact-select"><span>نوع الثوب</span><select disabled={orderLocked} value={thobeType} onChange={event=>changeThobeType(event.target.value)}>{thobeTypes.map(type=><option key={type}>{type}</option>)}</select></label><div className="vertical-fields">{bodyLengthInput()}{bodySingleFields.map(field=>measurementInput(field))}</div></article>

        <article className="measure-column sleeve-column"><header><span>02</span><h2>اليد</h2></header><div className="choice-switch"><button type="button" className={sleeveMode==="سادة"?"selected":""} disabled={orderLocked} onClick={()=>changeSleeveMode("سادة")}>سادة</button><button type="button" className={sleeveMode==="كبك"?"selected":""} disabled={orderLocked} onClick={()=>changeSleeveMode("كبك")}>كبك</button></div>{photoPicker(sleeveMode==="سادة"?"اليد السادة":"الكبك",sleeveMode==="سادة"?"أضف صورة اليد السادة":"أضف صورة الكبك")}<div className="vertical-fields">{sleeveBaseFields.map(field=>measurementInput(field))}{(sleeveMode==="سادة"?sleevePlainFields:sleeveCuffFields).map(field=>measurementInput(field))}</div></article>

        <article className="measure-column collar-column"><header><span>03</span><h2>الرقبة</h2></header><div className="choice-switch"><button type="button" className={collarMode==="قلاب"?"selected":""} disabled={orderLocked} onClick={()=>changeCollarMode("قلاب")}>قلاب</button><button type="button" className={collarMode==="سادة"?"selected":""} disabled={orderLocked} onClick={()=>changeCollarMode("سادة")}>سادة</button></div>{photoPicker(collarMode==="قلاب"?"القلاب":"الرقبة السادة",collarMode==="قلاب"?"أضف صورة القلاب":"أضف صورة الرقبة السادة")}<div className="vertical-fields collar-measures">{measurementInput("محيط الرقبة")}{collarMode==="قلاب"?<label className="compact-field"><span>مقاس القلاب</span><div className="dual-measure"><input className="numeric" disabled={orderLocked} value={measurements["مقاس القلاب الأول"]||""} onChange={event=>setMeasurements(current=>({...current,"مقاس القلاب الأول":latinDigits(event.target.value)}))} placeholder="3"/><i>—</i><input className="numeric" disabled={orderLocked} value={measurements["مقاس القلاب الثاني"]||""} onChange={event=>setMeasurements(current=>({...current,"مقاس القلاب الثاني":latinDigits(event.target.value)}))} placeholder="1.5"/><small>{unit}</small></div></label>:measurementInput("مقاس الرقبة السادة")}<label className="compact-select neck-option"><span>عدد أزرار الرقبة</span><select className="numeric" disabled={orderLocked} value={neckButtonCount} onChange={event=>setNeckButtonCount(event.target.value==="2"?"2":"1")}><option value="1">1</option><option value="2">2</option></select></label><label className="compact-select neck-option"><span>نوع أزرار الرقبة</span><select disabled={orderLocked} value={neckButtonType} onChange={event=>setNeckButtonType(event.target.value==="بلاستيك"?"بلاستيك":"طقطق")}><option>طقطق</option><option>بلاستيك</option></select></label></div></article>

        <article className="measure-column detail-column"><header><span>04</span><h2>الجيب والواجهة</h2></header><div className="double-photo">{photoPicker("الجيب","أضف صورة الجيب")}{photoPicker("السحب","السحب فارغ — اضغط للإضافة")}</div><div className="vertical-fields fabric-compact">{fabricFields.map(field=><label className="compact-field" key={field}><span>{field}</span><div><input className={field==="اسم القماش"?"":"numeric"} disabled={orderLocked} value={fabric[field]||""} onChange={event=>setFabric(current=>({...current,[field]:field==="اسم القماش"?event.target.value:latinDigits(event.target.value)}))} placeholder="—"/>{field==="طول الجنزور"&&<small>{unit}</small>}</div></label>)}</div><label className="compact-notes"><span>ملاحظة الخياط</span><textarea disabled={orderLocked} value={notes} onChange={event=>setNotes(event.target.value)} placeholder="تعليمات خاصة بالثوب"/></label></article>
      </section>

      <section className="compact-finance"><label><span>إجمالي السعر</span><input className="numeric" disabled={orderLocked} value={totalPrice} onChange={event=>setTotalPrice(latinDigits(event.target.value))}/></label><label><span>نوع الدفع</span><select disabled={orderLocked} value={paymentMethod} onChange={event=>setPaymentMethod(event.target.value)}><option>كاش</option><option>شبكة</option><option>تحويل</option></select></label><label><span>المدفوع الآن</span><input className="numeric" disabled={orderLocked} value={paidAmount} onChange={event=>setPaidAmount(latinDigits(event.target.value))}/></label><label><span>الخصم</span><input className="numeric" disabled={orderLocked} value={discount} onChange={event=>setDiscount(latinDigits(event.target.value))}/></label><div className="compact-remaining"><span>المتبقي</span><b className="numeric">{numberFormat.format(remaining)} ر.س</b></div></section>

      <section className="order-actions compact-order-actions"><button className="primary-action" type="button" disabled={savingInvoice||orderLocked} onClick={()=>void saveInvoice()}>{savingInvoice?"جارٍ الحفظ…":"حفظ الفاتورة"}</button><button type="button" disabled={!invoice||!orderLocked} onClick={()=>{setOrderLocked(false);setOrderMessage("وضع التعديل مفتوح")}}>تعديل</button><button type="button" disabled={savingInvoice} onClick={()=>void openPrintPreview("receipt")}>فاتورة السعر</button><button type="button" disabled={savingInvoice} onClick={()=>void openPrintPreview("laundry")}>فاتورة المغسلة</button><button type="button" disabled={savingInvoice} onClick={()=>void openPrintPreview("measurements")}>طباعة المقاس</button><button type="button" onClick={resetInvoice}>فاتورة جديدة</button>{orderMessage&&<p>{orderMessage}</p>}</section>
    </section>}
    {view==="settings"&&<section className="settings-page" dir="rtl">
      <div className="settings-title"><div><span>الإعدادات</span><h1>إعدادات التطبيق</h1><p>إدارة مكتبة الأشكال ومكان حفظ جميع بيانات المحل.</p></div><button type="button" onClick={()=>setView(currentCustomer?"order":"dashboard")}>رجوع</button></div>
      <section className="storage-card">
        <div className="storage-copy"><span>قاعدة بيانات المحل</span><h2>مكان حفظ البيانات</h2><p>الفواتير والعملاء والمقاسات والصور محفوظة معًا داخل ملف <b>tailor.sqlite</b>. انسخ المجلد كاملًا عند الانتقال إلى جهاز آخر.</p></div>
        <div className="storage-path"><small>المجلد المستخدم حاليًا</small><b dir="ltr">{storage?.folder||"جارٍ قراءة المكان…"}</b><small>ملف البيانات</small><span dir="ltr">{storage?.databasePath||"—"}</span><em>{storage?.isCustom?"مكان مخصص":"المكان الافتراضي للتطبيق"}</em></div>
        <div className="storage-actions"><button className="storage-copy-button" type="button" disabled={storageBusy||Boolean(currentCustomer)} onClick={()=>void chooseStorage("copy")}>{storageBusy?"جارٍ التنفيذ…":"نسخ البيانات الحالية إلى مجلد جديد"}</button><button type="button" disabled={storageBusy||Boolean(currentCustomer)} onClick={()=>void chooseStorage("use")}>ربط مجلد بيانات من جهاز سابق</button></div>
        {currentCustomer&&<p className="storage-warning">اخرج من فاتورة العميل أولًا قبل تغيير مكان قاعدة البيانات.</p>}{storageMessage&&<p className="storage-message">{storageMessage}</p>}
      </section>
      <div className="settings-layout"><form className="option-form" onSubmit={event=>void addDesignOption(event)}><h2>إضافة نوع جديد</h2><label><span>القسم</span><input list="category-list" value={settingsCategory} onChange={event=>setSettingsCategory(event.target.value)}/><datalist id="category-list">{categories.map(category=><option key={category} value={category}/>)}</datalist></label><label><span>اسم النوع</span><input value={optionName} onChange={event=>setOptionName(event.target.value)} placeholder="مثال: قلاب ملكي"/></label><label className="image-upload"><span>صورة النوع</span><input type="file" accept="image/*" onChange={event=>void selectImage(event)}/>{optionImage?<img src={optionImage} alt="معاينة الصورة"/>:<b>اختر صورة محفوظة في الكمبيوتر</b>}</label>{settingsError&&<p>{settingsError}</p>}<button className="save-option" type="submit">حفظ النوع والصورة</button></form><section className="option-library"><div className="category-tabs">{categories.map(category=><button className={settingsCategory===category?"selected":""} type="button" key={category} onClick={()=>setSettingsCategory(category)}>{category}</button>)}</div><div className="option-cards">{designOptions.filter(option=>option.category===settingsCategory).length===0&&<p>لا توجد أنواع في هذا القسم حتى الآن.</p>}{designOptions.filter(option=>option.category===settingsCategory).map(option=><article key={option.id}><img src={option.imageData} alt={option.name}/><div><b>{option.name}</b><small>{option.category}</small></div><button type="button" onClick={()=>void deleteDesignOption(option.id)}>حذف</button></article>)}</div></section></div>
    </section>}
    {pickerCategory&&<div className="picker-overlay" onMouseDown={()=>setPickerCategory(null)}><section className="picker-dialog" dir="rtl" onMouseDown={event=>event.stopPropagation()}><header><div><span>اختيار النوع</span><h2>{pickerCategory}</h2></div><button type="button" onClick={()=>setPickerCategory(null)}>×</button></header><div className="picker-options">{designOptions.filter(option=>option.category===pickerCategory).length===0&&<div className="picker-empty"><p>لا توجد صور مضافة لهذا القسم.</p><button type="button" onClick={()=>{setSettingsCategory(pickerCategory);setPickerCategory(null);setView("settings")}}>إضافتها من الإعدادات</button></div>}{designOptions.filter(option=>option.category===pickerCategory).map(option=><button type="button" key={option.id} onClick={()=>{setSelectedDesigns(current=>({...current,[pickerCategory]:option}));if(pickerCategory==="نوع الثوب"&&(thobeTypes as readonly string[]).includes(option.name))setThobeType(option.name);setPickerCategory(null)}}><img src={option.imageData} alt={option.name}/><b>{option.name}</b></button>)}</div>{selectedDesigns[pickerCategory]&&<button className="remove-choice" type="button" onClick={()=>{setSelectedDesigns(current=>({...current,[pickerCategory]:undefined}));setPickerCategory(null)}}>إلغاء اختيار هذا القسم</button>}</section></div>}
    {previewTarget&&currentCustomer&&<div className="preview-overlay" onMouseDown={()=>setPreviewTarget(null)}><section className={`preview-dialog ${previewTarget==="measurements"?"":"thermal-dialog"}`} onMouseDown={event=>event.stopPropagation()}><div className="preview-tools"><b>{previewTitle}</b><button type="button" onClick={()=>printSheet(previewTarget)}>طباعة الآن</button><button type="button" onClick={()=>setPreviewTarget(null)}>إغلاق</button></div><div className={`preview-sheets ${previewTarget==="measurements"?"":"thermal-preview"}`}>{previewTarget==="measurements"&&measurementSheets.map((sheet,index)=><MeasurementSheet key={index} {...sheet}/>)}{previewTarget==="receipt"&&<CustomerReceiptSheet customer={currentCustomer} invoice={invoice} thobes={outputDrafts} total={total} paid={paid} discount={discountValue} remaining={remaining} paymentMethod={paymentMethod} deliveryDate={deliveryDate}/>} {previewTarget==="laundry"&&outputDrafts.map((thobe,index)=><LaundryReceiptSheet key={index} customer={currentCustomer} invoice={invoice} thobe={thobe} index={index} total={outputDrafts.length} deliveryDate={deliveryDate}/>)}</div></section></div>}
    {view==="dashboard"&&historyOpen&&<div className="history-overlay" role="presentation" onMouseDown={()=>setHistoryOpen(false)}><section className="history-dialog" role="dialog" aria-modal="true" aria-labelledby="history-title" onMouseDown={event=>event.stopPropagation()}><div className="history-head"><div><span>تشغيل التطبيق</span><h2 id="history-title">سجل أوقات التشغيل</h2></div><label className="history-filter"><span>ابحث بالتاريخ الميلادي</span><input className="numeric" type="date" lang="ar-SA-u-ca-gregory-nu-latn" value={selectedDay} onChange={event=>setSelectedDay(event.target.value)}/></label><button type="button" onClick={()=>setHistoryOpen(false)} aria-label="إغلاق">×</button></div><div className="history-summary">{selectedDay?<>في <b className="numeric">{selectedDay}</b> فُتح التطبيق <strong className="numeric">{numberFormat.format(filteredHistory.length)}</strong> مرات</>:"اختر تاريخًا لعرض عدد مرات الفتح في ذلك اليوم."}</div><div className="history-list">{filteredHistory.length===0&&<p>{selectedDay?"لا توجد جلسات في التاريخ المختار.":"لا توجد جلسات مكتملة بعد."}</p>}{filteredHistory.map(item=><article className="history-row" key={item.key}><div><strong className="numeric">{dateFormat.format(item.start)}</strong><small className="numeric">هجريًا: {hijriDateFormat.format(item.start)}</small></div><div><span className="numeric">{timeFormat.format(item.start)} — {timeFormat.format(item.end)}</span><b className="numeric">{durationLabel(item.end.getTime()-item.start.getTime())}</b>{item.active&&<small>نشطة الآن</small>}</div></article>)}</div></section></div>}
    <div className="print-area"><div className="measurement-print-stack">{measurementSheets.map((sheet,index)=><MeasurementSheet key={index} {...sheet}/>)}</div>{currentCustomer&&<><CustomerReceiptSheet customer={currentCustomer} invoice={invoice} thobes={outputDrafts} total={total} paid={paid} discount={discountValue} remaining={remaining} paymentMethod={paymentMethod} deliveryDate={deliveryDate}/><div className="laundry-print-stack">{outputDrafts.map((thobe,index)=><LaundryReceiptSheet key={index} customer={currentCustomer} invoice={invoice} thobe={thobe} index={index} total={outputDrafts.length} deliveryDate={deliveryDate}/>)}</div></>}</div>
  </main>;
}
